---
ocp4_workload_openshift_ai_dashboard_config_settings:
  disableTracking: false
  disableModelRegistry: false
  disableModelCatalog: false
  disableKServeMetrics: false
  genAiStudio: true
  modelAsService: true
  disableLMEval: false

ocp4_workload_openshift_ai_dashboard_config_notebook_controller:
  enabled: true
  pvcSize: 20Gi

ocp4_workload_openshift_ai_hardware_profile_gpu_identifiers:
- defaultCount: '1'
  displayName: CPU
  identifier: cpu
  maxCount: '8'
  minCount: 1
  resourceType: CPU
- defaultCount: 12Gi
  displayName: Memory
  identifier: memory
  maxCount: 16Gi
  minCount: 1Gi
  resourceType: Memory
- defaultCount: 1
  displayName: GPU
  identifier: nvidia.com/gpu
  maxCount: 4
  minCount: 1
  resourceType: Accelerator

